plugins:
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable

# Good documentation welcome, but not required
Style/Documentation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/LambdaCall:
  Enabled:
    EnforcedStyle: braces

Style/RedundantSelf:
  Enabled: false

Layout/LineLength:
  Enabled:
    max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/NestedGroups:
  Enabled: false
