plugins:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# Good documentation welcome, but not required
Style/Documentation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/LambdaCall:
  Enabled:
    EnforcedStyle: braces

Style/RedundantSelf:
  Enabled: false

Layout/LineLength:
  Enabled:
    max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Security/Eval:
  Exclude:
    - spec/**/*.rb
