---
name: rake
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      exclude:
        - { os: macos-latest, ruby: '2.5' }
      include:
        - { os: macos-13, ruby: '2.5' }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: bundle install --no-color
      - run: bundle exec rake
