---
name: rake
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: bundle install --no-color
      - run: bundle exec rake
